### ISSUE TITLE
Get state of running in-terminal process

### ISSUE THREAD

**Issue by wclr** [Tyriar/vscode-terminal-api-example#1]
Hello, nice terminal API, thanks for that.
Is it possible somehow to the state of running launched in terminal process (has it finished/stopped filed)?

though I believe it referee to workbench API.

**Comment by Tyriar** [comment]
We're looking into how best to do this, it's not a trivial thing though since we're talking to a process which is talking to bash which is talking to another program (which could be another shell for example). The child process(es) of the shell application will likely be exposed in some way in the future to accomplish something similar. I'll close this off for now but keep read the iteration plans and release notes for potential updates on the API.

**Comment by wclr** [comment]
thanks. I found https://github.com/indexzero/ps-tree that can be used to get child processes pids created by terminal so it is possible to get their running/stopped state, but no more (some internal state).

Is it possible to attach (analyze) to console output?

**Comment by Tyriar** [comment]
Currently no but I believe this is what the debug extensions want to accomplish.
